version: 0.2

env:
  variables:
    PROJECT: "dev-mportal"
  parameter-store:
    NEWRELIC_LICENSE: "/build/nrlicense"

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - sh /usr/local/bin/dockerd-entrypoint.sh
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - export REPOSITORY_URI="597408147832.dkr.ecr.us-east-1.amazonaws.com/$PROJECT"
      - export COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - aws s3 cp s3://xpresso-build-tools/newrelic-netcore.tar.gz .
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest --build-arg PROJECT=$PROJECT  --build-arg NEWRELIC_LICENSE=$NEWRELIC_LICENSE   .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $PROJECT $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
    #testing3
